config/routes.rb
Princess::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'yachts#index'

  resources 'rates', only: :index
  resources 'yachts', path: '/', only: :show
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/base_photo.rb
class BasePhoto < ActiveRecord::Base
  abstract = true

  attr_accessible :yacht_id, :attachment, :attachment_cache

  set_table_name 'photos'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :phone, :photo

  mount_uploader :photo, ContactPhotoUploader

  validates :first_name, :last_name, :email, :phone, :photo, presence: true
end

app/models/cover.rb
class Cover < BasePhoto
  belongs_to :yacht, inverse_of: :cover

  mount_uploader :attachment, CoverUploader

  validates :attachment, presence: true
end

app/models/currency_market.rb
module CurrencyMarket

  SOURCE = 'http://www.cbr.ru/scripts/XML_daily.asp'
  RATES  = {
    'GBP' => {
      nominal: 1,
      value: 54
    },
    'USD' => {
      nominal: 1,
      value: 33
    },
    'EUR' => {
      nominal: 1,
      value: 45
    }
  }

  def self.rates
    if data = Rails.cache.read(cache_key)
      data
    else
      data = fetch

      Rails.cache.write(cache_key, data, expires_in: 1.day)

      data
    end
  end

  private

    def self.cache_key
      "currency_market_at_#{Time.zone.now.strftime("%Y_%m_%d")}"
    end

    def self.fetch
      needed_rates = RATES.keys
      result       = HashWithIndifferentAccess.new

      begin
        raw_rates = HTTParty.get(SOURCE)['ValCurs']['Valute']

        raw_rates.each do |raw_rate|
          if RATES.include? raw_rate['CharCode']
            result[raw_rate['CharCode'].to_sym] = {
              nominal: raw_rate['Nominal'].to_i,
              value: raw_rate['Value'].gsub(',', '.').to_f
            }
          end
        end
      rescue Exception => e
        Rails.logger.error "CurrencyMarket: #{e.message}"
      ensure
        needed_rates.each do |rate|
          unless result.has_key? rate.to_sym
            result[rate.to_sym] = RATES[rate]
          end
        end
      end

      result
    end

end

app/models/photo.rb
class Photo < BasePhoto
  attr_accessible :yacht_id, :attachment, :attachment_cache

  belongs_to :yacht, inverse_of: :photos

  mount_uploader :attachment, PhotoUploader
end

app/models/scheme.rb
class Scheme < BasePhoto
  belongs_to :yacht, inverse_of: :schemes

  mount_uploader :attachment, SchemeUploader

  validates :attachment, presence: true
end

app/models/yacht.rb
class Yacht < ActiveRecord::Base

  SHORT_INFO = [:name, :year, :length, :width, :weight, :draft, :fuel_tank,
                :water_tank, :engine, :engines_count, :capacity, :speed,
                :hours, :location, :color, :cabins, :bunks, :description,
                :customs, :price, :currency, :status, :cruising_speed]
  FULL_INFO  = [:equipment, :spare_parts, :comments, :options, :interiors]
  CURRENCIES = [:EUR, :GBP, :USD]

  attr_accessible *(SHORT_INFO + FULL_INFO)
  attr_accessible :cover_attributes
  attr_accessible :schemes_attributes
  attr_accessible :photos_attributes

  has_one  :cover,          dependent: :destroy, inverse_of: :yacht
  has_many :photos,         dependent: :destroy, inverse_of: :yacht
  has_many :schemes,        dependent: :destroy, inverse_of: :yacht

  accepts_nested_attributes_for :cover
  accepts_nested_attributes_for :schemes, allow_destroy: true
  accepts_nested_attributes_for :photos,  allow_destroy: true

  validates :name, :description, :currency, :equipment, :spare_parts, :comments,
            :options, :interiors, presence: true
  validates :cover, presence: true
  validates :year, numericality: { only_integer: true,
                                   greater_than_or_equal_to: 1990,
                                   less_than_or_equal_to: Date.current.year },
                   allow_blank: true
  validates :length, :width, :weight, :draft, :capacity, numericality: true,
                                                         allow_blank: true
  validates :fuel_tank, :water_tank, :engines_count, :speed, :hours, :cruising_speed,
            numericality: { only_integer: true }, allow_blank: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }
  validates :currency, inclusion: { in: CURRENCIES.map{ |v| v.to_s } }

  state_machine :status, initial: :not_published do
    event :publish do
      transition (all - :for_sale) => :for_sale
    end

    event :edit do
      transition (all - :not_published) => :not_published
    end

    event :sold do
      transition (all - :sold_out) => :sold_out
    end
  end

  scope :short_info,    -> { select(SHORT_INFO) }
  scope :full_info,     -> { select(SHORT_INFO + FULL_INFO) }
  scope :for_sale,      -> { where(status: 'for_sale') }
  scope :sold_out,      -> { where(status: 'sold_out') }
  scope :not_published, -> { where(status: 'not_published') }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  def index
    render json: CurrencyMarket.rates
  end

end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController

  before_filter :collection,     only: :index
  before_filter :fetch_contacts, only: :show
  before_filter :resource,       only: :show


  def index; end

  def show
    respond_to do |format|
      format.html { render :show, layout: false }
      format.pdf
    end
  end

  protected

    def collection
      @yachts ||= Yacht.includes(:cover).for_sale

      rates = CurrencyMarket.rates

      @yachts.sort! do |a, b|
        if a.currency == 'EUR'
          price_a = a.price
        else
          price_a = a.price * rates['EUR']['value']
          price_a = price_a / rates[a.currency]['value']
        end

        if b.currency == 'EUR'
          price_b = b.price
        else
          price_b = b.price * rates['EUR']['value']
          price_b = price_b / rates[b.currency]['value']
        end

        price_b <=> price_a
      end

      @yachts = YachtDecorator.decorate_collection(@yachts)
    end

    def resource
      @yacht ||= Yacht.includes(:cover, :photos, :schemes)
                      .find(params[:id])
                      .decorate
    end

    def fetch_contacts
      @contacts = Contact.first.decorate
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def wicked_pdf_image_tag_for_public(img, options={})
    if img[0] == "/"
      new_image = img.slice(1..-1)
      image_tag "file://#{Rails.root.join('public', new_image)}", options
    else
      image_tag "file://#{Rails.root.join('public', 'images', img)}", options
    end
  end

end

app/helpers/markdown_helper.rb
module MarkdownHelper

  OPTIONS = { autolink: true, no_styles: true, safe_links_only: true, filter_html: true }

  def markdown(source, html_safe = true)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, MarkdownHelper::OPTIONS)

    html_safe? ? renderer.render(source).html_safe : renderer.render(source)
  end

end

app/views/admin/contacts/edit.html.slim
= semantic_form_for resource, url: admin_contacts_update_path, method: :post do |f|
  = f.inputs 'Основные данные' do
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :phone

  = f.inputs 'Фотография' do
    - hint = "Рекомендуемый размер фотографии: от 400x400 (отношение сторон 1:1)<br />"
    - if resource.photo?
      = f.input :photo, as: :file, hint: "#{hint}#{image_tag(resource.photo_url(:large))}".html_safe
    - else
      = f.input :photo, as: :file, hint: hint

  = f.actions

app/views/layouts/_divider.slim
#divider-wrapper
  #divider
    #divider-inner
      hr

app/views/layouts/_footer.slim
#footer-wrapper
  #footer
    #description
    / hr
    / #sponsors
      / .sponsor.princess: a href='http://www.princessyachts.com/': .logo
      / .sponsor.bayliner: a href='http://global.bayliner.com/': .logo
      / .sponsor.moody: a href='http://www.moodyboats.com/': .logo
      / .sponsor.hense: a href='http://www.hanseyachts.com/ru': .logo
    hr
    #copyright
      p
        ' http://ibs-brokerage.com

app/views/layouts/_header.slim
#header-wrapper
  header#header
    #header-inner
      section#header-logo
        = image_tag 'logo.png', width: 300
      nav#header-menu
        ul.items
          li.search
            a#search-switcher href='javascript:void(0);'
              ' Поиск
              i.icon
      nav#search
        i.arrow
        form#search-form
          span.control
            label for='name' Название:
            span.divider
            input type='text' name='name'
          span.control
            label for='price' Цена:
            span.divider
            select name='sign'
              option value='>' selected=true Больше
              option value='=' Равно
              option value='<' Меньше
            span.divider
            input type='text' name='price'
            span.divider
            select name='currency'
              option value='EUR' selected=true EUR
              option value='GBP' GBP
              option value='USD' USD
          span.control
            input type='submit' value='Искать'
            span.divider
            input type='reset' value='Отменить'

app/views/layouts/_toolbar.slim
#toolbar-wrapper
  #toolbar
    #toolbar-inner
      #view
        ul.items#view-menu
          li Вид
          li
            a.selected data-view='two'
              i.icon
          li
            a data-view='three'
              i.icon
      #filter.visible
        ul.items
          li#sort-menu
            a href='javascript:void(0);'
              ' Сортировать
              i.icon
            ul.submenu.wide
              li
                i.arrow
                a data-parameter='year' href='javascript:void(0);' По году постройки
              li
                a data-parameter='length' href='javascript:void(0);' По размеру
              li
                a data-parameter='price' href='javascript:void(0);' По цене
          li.divider
          li#currency-menu
            a href='javascript:void(0);'
              ' Валюта
              i.icon
            ul.submenu
              - Yacht::CURRENCIES.each_with_index do |currency, index|
                li
                  - if index.zero?
                    i.arrow
                  a href="javascript:void(0);" data-currency=currency.to_s.downcase = currency
      #details-menu-wrapper
        ul.items
          li#details-menu
            a href='javascript:void(0);'
              ' Подробнее
              i.icon
            ul.submenu
              li
                i.arrow
                a href='javascript: void(0);' data-parameter='description' Описание
              li
                a href='javascript: void(0);' data-parameter='mobile-photos' Фотографии
              li
                a href='javascript: void(0);' data-parameter='data' Данные
              li
                a href='javascript: void(0);' data-parameter='interiors' Интерьер
              li
                a href='javascript: void(0);' data-parameter='comments' Комментарий
              li
                a href='javascript: void(0);' data-parameter='manager' Менеджер
              li
                = link_to 'Скачать PDF', '', class: 'pdf', target: '_blank'
          li#details-close
            a#yacht-close href='javascript:void(0);' На главную
          .clear
      .clear

app/views/layouts/_top.slim
#top-wrapper
  #top
    #top-inner
      a href='javascript:void(0);' Наверх

app/views/layouts/application.html.slim
doctype html
erb:
  <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
  <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
  <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

head
  meta charset='utf-8'
  meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'

  title Brokerage

  meta name='description' content=''
  meta name='viewport' content='width=device-width, initial-scale=1.0'

  = stylesheet_link_tag 'application', media: :all
  = csrf_meta_tag
body
  #wrapper
    = render 'layouts/header'
    = render 'layouts/toolbar'
    = render 'layouts/divider'

    #content-wrapper
      #content
        #content-inner.two-column
          = yield

    = render 'layouts/top'
  = render 'layouts/footer'
  = javascript_include_tag 'application'
erb:
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter23491207 = new Ya.Metrika({id:23491207,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
  </script>
  <noscript><div><img src="//mc.yandex.ru/watch/23491207" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->
  </html>

app/views/yachts/index.html.slim
- @yachts.each_with_index do |yacht, index|
  figure.yacht-preview.visible data-yacht-id=yacht.id data-index=yacht.index_data
    = yacht.cover.preview
    figcaption
      h3 = yacht.name
      = yacht.price_html
  - if (index + 1) < @yachts.length
    - if index % 2 == 1
      hr

app/views/yachts/show.html.slim
.yacht-wrapper
  .yacht data-yacht-id=@yacht.id
    .yacht-inner
      .yacht-content
        .desktop
          .header
            .title
              h1 = @yacht.name
            .close
              a.icon href='javascript:void(0);'
          .left
            .photos
              .fotorama data-nav='thumbs' data-loop='true'
                a href=@yacht.cover.photo_url = @yacht.cover.thumb
                - @yacht.photos.each do |p|
                  a href=p.photo_url = p.thumb
                - @yacht.schemes.each do |s|
                  a href=s.preview_url = s.thumb
            .description
              = @yacht.description_html
          .right
            .stats
              .tabbable
                ul.tabs
                  li.active data-tab='data'
                    .inner Данные
                  li data-tab='interiors'
                    .inner Интерьер
                  li data-tab='comments'
                    .inner Замечания
                .tab-content
                  .tab-pane.active data-tab="data"
                    table
                      - if @yacht.year?
                        tr
                          th Год выпуска
                          td = @yacht.year
                      - if @yacht.length?
                        tr
                          th Длина
                          td = @yacht.length
                      - if @yacht.width?
                        tr
                          th Ширина
                          td = @yacht.width
                      - if @yacht.draft?
                        tr
                          th Осадка
                          td = @yacht.draft
                      - if @yacht.weight?
                        tr
                          th Вес
                          td = @yacht.weight
                      - if @yacht.color?
                        tr
                          th Цвет корпуса
                          td = @yacht.color
                      - if @yacht.engine?
                        tr
                          th Двигатель
                          td = @yacht.engine
                      - if @yacht.capacity?
                        tr
                          th Мощность
                          td = @yacht.capacity
                      - if @yacht.hours?
                        tr
                          th Моточасы
                          td = @yacht.hours
                      - if @yacht.fuel_tank?
                        tr
                          th Запас топлива
                          td = @yacht.fuel_tank
                      - if @yacht.water_tank?
                        tr
                          th Запас воды
                          td = @yacht.water_tank
                      - if @yacht.cruising_speed?
                        tr
                          th Круизная скорость
                          td = @yacht.cruising_speed
                      - if @yacht.speed?
                        tr
                          th Максимальная скорость
                          td = @yacht.speed
                      - if @yacht.location?
                        tr
                          th Местоположение
                          td = @yacht.location
                      tr
                        th Статус
                        td = @yacht.customs
                  .tab-pane data-tab="interiors"
                    - if @yacht.cabins? or @yacht.bunks?
                      table
                        - if @yacht.cabins?
                          tr
                            th Каюты
                            td = @yacht.cabins
                        - if @yacht.bunks?
                          tr
                            th Спальные места
                            td = @yacht.bunks
                    - if @yacht.interiors?
                      br
                      = @yacht.interiors_html
                  .tab-pane data-tab="comments"
                    - if @yacht.comments?
                      = @yacht.comments_html
              .pdf-wrapper
                .pdf
                  = link_to 'Скачать PDF буклет', yacht_path(@yacht, format: :pdf), class: 'pdf-inner', target: '_blank'
            .manager
              h1.title Связь с менеджером
              .avatar
                = image_tag @contacts.photo_url(:small)
              .info
                p = @contacts.full_name
                p.phone = @contacts.phone
                p.email = mail_to @contacts.email
        .mobile.description
          .description
            .photo = @yacht.cover.photo
            .title = @yacht.name
            .price = @yacht.price_html
            .notes = @yacht.description_html
          .mobile-photos
            = @yacht.cover.photo
            - @yacht.photos.each do |p|
              = p.photo
            - @yacht.schemes.each do |s|
              = s.preview
          .data
            dl
              - if @yacht.year?
                dt Год выпуска
                dd = @yacht.year
              - if @yacht.length?
                dt Длина
                dd = @yacht.length
              - if @yacht.width?
                dt Ширина
                dd = @yacht.width
              - if @yacht.draft?
                dt Осадка
                dd = @yacht.draft
              - if @yacht.weight?
                dt Вес
                dd = @yacht.weight
              - if @yacht.color?
                dt Цвет корпуса
                dd = @yacht.color
              - if @yacht.engine?
                dt Двигатель
                dd = @yacht.engine
              - if @yacht.capacity?
                dt Мощность
                dd = @yacht.capacity
              - if @yacht.hours?
                dt Моточасы
                dd = @yacht.hours
              - if @yacht.fuel_tank?
                dt Запас топлива
                dd = @yacht.fuel_tank
              - if @yacht.water_tank?
                dt Запас воды
                dd = @yacht.water_tank
              - if @yacht.cruising_speed?
                dt Круизная скорость
                dd = @yacht.cruising_speed
              - if @yacht.speed?
                dt Максимальная скорость
                dd = @yacht.speed
              - if @yacht.location?
                dt Местоположение
                dd = @yacht.location
              dt Статус
              dd = @yacht.customs
          .interiors
            - if @yacht.cabins? or @yacht.bunks?
              - if @yacht.cabins?
                p
                  span.title Каюты:&nbsp;
                  = @yacht.cabins
              - if @yacht.bunks?
                p
                  span.title Спальные места:&nbsp;
                  = @yacht.bunks
            - if @yacht.interiors?
              br
              = @yacht.interiors_html
          .comments
            - if @yacht.comments?
              = @yacht.comments_html
          .manager
            .avatar = image_tag @contacts.photo_url(:large)
            p.name = @contacts.full_name
            p.phone = @contacts.phone
            p.email = mail_to @contacts.email